# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eLC0a3mi6e4i5TBVrbys5UyWHw6pTfuq

# **Necessary imports**
"""

import numpy as np
import pandas as pd
import os, sys
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier

"""# Reading the data into DataFrame"""

df = pd.read_csv('parkinsons.csv')
df.head()

"""# Getting features and labels"""

features = df.loc[:,df.columns != 'status'].values[:,1:]
labels = df.loc[:,'status'].values

"""# Getting the count of 0's and 1's in the status column"""

print(labels[labels==1].shape[0], labels[labels==0].shape[0])

"""# Initialize a MinMaxScaler and scaling the features to between -1 and 1 to normalize them"""

scaler = MinMaxScaler((-1,1))
x = scaler.fit_transform(features)
y = labels

"""# Spliting the data into train and test"""

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=7)

"""# Initialize an XGBClassifier and train the model"""

model = XGBClassifier()
model.fit(x_train,y_train)

"""# Generating y_preds and accuracy for the model"""

y_preds = model.predict(x_test)
print(accuracy_score(y_test,y_preds)*100)